export const PUBX_CONFIG = {
  LAYOUT_KEY: "LAYOUT_KEY",
  CONTROL_PANEL_KEY: "CONTROL_PANEL_KEY",
  ROM_COLLECTION_KEY: "ROM_COLLECTION_KEY",
  SAVES_STATES_KEY: "SAVE_STATES_KEY",
  INFO_MODAL_KEY: "INFO_MODAL_KEY"
};
